### ISSUE TITLE
"ErrorCode":"6", "Message":"Неверный статус карты."

### ISSUE THREAD

**Issue by EvgenyPlaksin** [Tinkoff/AcquiringSdkAndroid#116]
Здравствуйте. Пытаюсь протестировать привязку карт, получаю такой ответ в логах :
`{"Success":false,"ErrorCode":"6","Message":"Неверный статус карты.","TerminalKey":"---DEMO","RequestKey":"-----","CustomerKey":"--------"}`
Тестирую вроде как правильно, isDeveloperMode = false, terminalKey с демо.

В чём может быть проблема?

**Comment by EvgenyPlaksin** [comment]
Я заметил, что запрос двоится, и в логах сначала приходит успех, а потом ошибка.
![image](https://user-images.githubusercontent.com/94696816/195986303-ae513e3b-f5f8-4367-8e74-c341ecbe3053.png)

**Comment by EvgenyPlaksin** [comment]
Также приложу код:

Инициализация sdk:
```kotlin
class EcoTaxiApplication : Application() {

    override fun onCreate() {
        super.onCreate()
 
                val publicKey = "-----"
        tinkoffAcquiring = TinkoffAcquiring(this, "------", publicKey)
        AcquiringSdk.isDeveloperMode = false
        AcquiringSdk.isDebug = true
    }

    companion object {
         var tinkoffAcquiring: TinkoffAcquiring? = null
            private set
    }

```

Запуск экрана с привязкой карт:
```kotlin
 val attachCardOptions =
                                        AttachCardOptions().setOptions {
                                            customerOptions {
                                                checkType = CheckType.NO.name
                                                customerKey = viewModel.userId
                                                email = viewModel.email
                                            }
                                            featuresOptions {
                                                handleCardListErrorInSdk = true
                                                handleErrorsInSdk = true
                                                validateExpiryDate = true
                                                tinkoffPayEnabled = true
                                                userCanSelectCard = true
                                                useSecureKeyboard = false
                                                darkThemeMode = DarkThemeMode.DISABLED
                                                theme = R.style.PaymentDialog
                                                localizationSource = AsdkSource(Language.RU)
                                            }
                                        }

                                    tinkoffAcquiring?.openAttachCardScreen(
                                        requireActivity(),
                                        attachCardOptions,
                                        ATTACH_CARD_REQUEST_CODE
                                    )
```

Проблема всё ещё актуальна, никак не могу разобраться с этим

**Comment by jQwout** [comment]
Здравствуйте, взяли в работу ваше обращение. Разбираемся.

**Comment by AnMado13** [comment]
Здравствуйте! Такую ошибку можно получить в том случае, если вы указываете CustomerKey, по которому не было совершенно ни одной успешной оплаты. В таком случае, этот CustomerKey еще не зарегистрирован. С одной стороны карта успешно прошла весь флоу CheckType = NO, с другой стороны -- в базах данных не был найден CustomerKey; по итогу не ясно, к чему привязывать карту. Вот и возвращается неверный статус.
Как этого всего избежать:
1) Обычно, пока CustomerKey не зарегистрирован, у пользователя отключают возможность добавления карты. Тогда пользователь всегда попадает на платежную форму и вынужден совершить платеж, тем самым зарегистрировать свою ключ. После чего он может свободно привязывать как угодно свои карты.
2) Можно также изменить способ привязки карты. Вы можете выбрать CheckType = HOLD, 3DS или 3DSHOLD. Тогда каждый раз при привязке всегда будет списываться 0 руб и отменяться (1 руб для карт МИР). Соответственно тогда ваш CustomerKey будет зарегистрирован, ибо была успешная оплата. 

Если посмотреть с другой стороны, то вывод такой. Если используется совсем новый CustomerKey, то при добавлении карты запрос v2/AddCard в ответе должен возвращать PaymentId -- это как подтверждение того, что был проведен некий платеж и тем самым прошла регистрация CustomerKey. В противном случае, если PaymentID не пришел, можно ожидать ошибку с бэка о неверном статусе.

**Comment by EvgenyPlaksin** [comment]
Здраствуйте, благодарю за ответ, всё заработало. Думаю, issue можно закрывать
