### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by Tar4s** [Tinkoff/AcquiringSdkAndroid#133]
Наткнулся на ситуацию, когда выполняю метод `Cancel` при заранее некорректных условиях - сумма возврата больше чека (тестирую API), при которой получаю `NetworkException` в котором нет никакой нужной мне информации для обработки ошибки.

И это некорректное поведение, так как данный тип экспешена используется на канальном уровне ошибки (из [комментария](https://github.com/Tinkoff/AcquiringSdkAndroid/blob/6a55ce34fe178f502cd40ef2c905f812980dc745/core/src/main/java/ru/tinkoff/acquiring/sdk/exceptions/NetworkException.kt#L20) к коду видно)

При ручном исполнении запроса Cancel через Postman получаю **нужную** структуру с описанием деталей ошибки:
```
{
    "Success": false,
    "ErrorCode": "330",
    "Message": "Неверные параметры.",
    "Details": "Сумма в запросе больше чем в оригинальной транзакции"
}
```

Метод `Cancel` с неверными параметрами возвращает код ошибки `400`:
![image](https://user-images.githubusercontent.com/13135957/201442259-50802b68-18e1-4991-83b6-a404d526584a.png)

А судя по [коду обработки запросов](https://github.com/Tinkoff/AcquiringSdkAndroid/blob/7bde000699169b1e3366bd4ace8c55a9b5eaa4c6/core/src/main/java/ru/tinkoff/acquiring/sdk/network/NetworkClient.kt#L91), даже когда нет проблем с сетью, но фактура запроса неверная мы всегда получаем `NetworkException`

Можно ли исправить ситуацию?

**Comment by Tar4s** [comment]
@IlnarH

**Comment by AnMado13** [comment]
Добрый день!

В ASDK на текущий момент мы не поддерживаем работу с методом v2/Cancel, поэтому не интегрируем его в компоненту. Любая отмена платежа должна осуществляться на бэкенде мерчанта. Т.о. вполне ожидаемо, что АСДК вернет NetworkException, ведь АСДК в принципе не заточен на работу с v2/Cancel и обработкой его ответов. 
На данный момент у нас нет в планах менять данный подход.

С уважением, Команда ASDK
