### ISSUE TITLE
Возвращение rebillId при первом платеже

### ISSUE THREAD

**Issue by VITYQ** [Tinkoff/AcquiringSdkAndroid#135]
_Версия Tinkoff Acquiring = 2.9.0_

## Цель
Иметь rebillId пользователя после первого платежа, для оформления подписки в сервисе

## Кейс
_View написан на compose (если это как-то влияет)_

в orderOptions флаг recurrentPayment = true
- Производится первая оплата в приложении. 
- Пользователя переводит на вебвью с просьбой ввести код из пуша. 
- После успешного ввода, производится снятия средств со счета, после этого пользователь возвращается в приложение.
- В onActivityResult я отслеживаю все extras

**Extras при первом платеже с привязкой карты через webview**
```
extra - key: extra_card_id - null
extra - key: extra_rebill_id - null
extra - key: extra_payment_id - 199224****
```
rebillId = null

При этом, если провести вторую оплату с уже привязанной карты, то нам возвращается rebillId

**Extras при втором и последующих платежах**
```
extra - key: extra_card_id - null
extra - key: extra_rebill_id - 119505****
extra - key: extra_payment_id - 199226****
```

Вопрос - как получить rebillId при первом платеже?

**Comment by jQwout** [comment]
Здравствуйте, можете описать поподробнее, к примеру, хочется понять,какой платежной системы была карта, это поможет.

Композ точно не при чем.

**Comment by VITYQ** [comment]
Тестировалось на MasterCard, изначально карта не привязана по CustomerKey. Первый платеж не возвращает rebillId, остальные возвращают. К сожалению, больше ничего сказать не могу

По итогу решили действовать путем: Привязываем карту на клиенте -> Бек берет rebillId с Api по привязанной карте
