### ISSUE TITLE
Отключить сворачивание формы при нажатии вне формы

### ISSUE THREAD

**Issue by VITYQ** [Tinkoff/AcquiringSdkAndroid#144]
Экран привязки карты имеет огромную пустую область, куда пользователь может ненароком нажать, из-за чего процесс привязки придется начинать сначала. Не лучший UX

Есть ли способ отключить сворачивание окна при нажатии вне? Если нет, то хотелось бы иметь такую возможность

![image](https://user-images.githubusercontent.com/37942022/204526619-8a26c7b0-53fe-4f92-a174-c150d165f92b.png)

**Comment by IlnarH** [comment]
Экран привязки карты будет переделан в рамках редизайна, релиз планируется в течение пары месяцев.

**Comment by AnMado13** [comment]
Добрый день! 

Дополню ответ. Экран на скриншоте устаревший. Дело в том, что ранее была проблема, при привязке карт МИР все шло по устаревшему флоу Loop_Confirmation (списывание случайно суммы и тд, как на экране со скриншота), однако должно идти по 3ds флоу. На стороне ASDK  были сделаны доработки (добавлена поддержка 3ds v2 при привязке карты) и большая часть карт МИР теперь идут по необходимому флоу: поэтому экран со скриншота у них не появляется. Тем не менее, для карт МИР с 3ds v1 проблема осталась, но на стороне backend (приходит устаревший статус). В скором времени эту проблему решат, поэтому указанный экран перестанет отображаться даже на ранних версиях: перестанет приходить устаревший статус, который инициализирует экран со скриншота; данный экран не будет более отображаться.

С уважением, Команда ASDK

**Comment by VITYQ** [comment]
Хорошо, спасибо.

Но пока главный вопрос - можно ли отключить скрытие экрана при нажатии вне?

**Comment by IlnarH** [comment]
На текущий момент - нет.
