### ISSUE TITLE
СБП GA 2

### ISSUE THREAD

**Issue by SeAtTink** [Tinkoff/AcquiringSdkAndroid#147]
Добрый день ! 
Подскажите пожалуйста,
1) Как работает SDK с теми банками, что поменяли диплинк схему? Например, есть пользователи, у которых осталось старое приложение Сбера, а затем они поставили новое приложение через iMazing. Обработает ли SDK такие ситуации динамически или нужно ставить новую версию SDK?
2) Ранее мы подключали оплату через СБОЛ, при возврате в наше приложение мы должны были запрашивать у бэка самостоятельно статус оплаты. При работе с СБП нам точно не нужно делать доп. экран с ожиданием статуса оплаты?
3) Кастомизация списка банковских приложений: есть или нет? Что мы можем визуально кастомизировать кроме кнопки СБП? 
4) Что будет, если мы захотим использовать свой дизайн для диалога, имеет ли смысл тогда вообще использовать SDK?
5) Вопрос про налоги, что делать с обязательными полями, когда нам не нужно передавать налоги?
6) "Кастомизация дизайна через SDK
Есть ли возможность кастомизации списка с выбором банка для оплаты через СБП и вообще управлять дизайном BottomSheet?"
7) Модальное окно "Ожидаем оплаты платежа" это часть СДК? Можно убрать? Как на разных платформах будет работать?

**Comment by jQwout** [comment]
Добрый вечер.

1. SDK проверяет системным методом, какие приложение поддерживают схему, утверждённой СБП, а так же частные случаи . Так же есть возможность получить список с сайта nspk (есть метод в SDK) Список приложений посмотреть здесь. - https://qr.nspk.ru/.well-known/assetlinks.json . Это Логика не меняется от версии к версии.  
Про iMazing - вы скорее всего ошиблись платформой, и данный вопрос уже задан в 
https://github.com/Tinkoff/AcquiringSdk_IOS/issues/229

2. После оплаты по СБП при возврате в приложение мерчанта SDK самостоятельно вызывает метод проверки статуса платежа и возвращает статус оплаты через колбэк; если вы хотите принудительно проверить статус , можете вызвать `AcquiringSdk#getState`

3. Не предполагается, но в ближайшее время будет редизайн  

4. Нужно подробнее узнать о вашем кейсе, но вы всегда можете реализовать интерфейсную часть на ваше усмотрение, пользуясь только `:core` модулем

5. Хотели бы побольше информации по кейсу. Параметр `Taxation` не является обязательным, параметр `Tax` можно обьявить как `NONE`

6. Список с банками не кастомизируется.

7. Часть SDK. Убрать нельзя

**Comment by SeAtTink** [comment]
Добрый день !
Благодарю за ответы, появились дополнительные вопросы:
1) Можно ли кастомизировать модальное окно "Ожидаем оплаты платежа"
2) Есть ли тестовая среда для SDK, какие методы можно протестировать на тесте ?

**Comment by jQwout** [comment]
Добрый день!

1. Нет
2. В Сэмпле проекта показаны все примеры работы с асдк - привязка карт, оплата по карте(прохождение 3ds и тд), а так же оплата по тинькофф пей и оплата по сбп.  Но, что бы проверить полный е2е цикл для 2 крайних вариантов - вам нужно получить тестовое клиентское приложение Тинькофф, развернутое на тестовом контуре, этого команда ASDK. предоставить не сможет.
