### ISSUE TITLE
Привязка карты через МИР сопровождается платежом в 0$

### ISSUE THREAD

**Issue by VITYQ** [Tinkoff/AcquiringSdkAndroid#162]
Кейс такой, что при привязке пользователем карты в приложении его отправляет на вебвью, где необходимо ввести код из пуша/смс. В случае с привязкой МИР, в форме выводится 0$, когда при привязке Visa/MasterCard выводится сумма 1-2 рубля. 
Данное поведение происходит с картами любого банка (тестировали Тинькофф, Сбер, Альфа)
Привязка через 3DS_HOLD. 
Как это можно объяснить и возможно ли привязывать карту МИР с отображением 0Р, а не 0$?

**Comment by jQwout** [comment]
Здравствуйте, вы имеете ввиду в форме webview? можете приложить скрин?

**Comment by VITYQ** [comment]
Да, в форме WebView.

Такое поведение замечено на Android и на Ios

![image](https://user-images.githubusercontent.com/37942022/208506101-530e32cb-6ad3-43f2-9cc6-ee9e43fb9c34.png)
![image](https://user-images.githubusercontent.com/37942022/208506154-ea743c60-62e4-4dd2-9202-5a8625c7f6c9.png)

**Comment by AnMado13** [comment]
Добрый день!

Visa и MasterCard идут по флоу 3ds версии 1, поэтому у них списывается случайная сумма от 1 до 2р. 
Карты МИР идут по флоу 3ds версии 2, поэтому у них всегда списывается нулевая сумма. 
Сама же форма в web-view от нас никак не зависит. Что банк нам пришлет, то и отображаем. Поэтому usd  или р. -- зависит сугубо от банка. Так как сумма нулевая, то вполне могу допустить, что у банка стандартный объект нулевой суммы -- это 0 usd, а не 0р. Впрочем, это лишь мое предположение. 
Исправить на своей мы это никак не можем, ибо контент веб-вью зависит полностью от банка, а нет асдк.

С уважением, команда ASDK
