### ISSUE TITLE
Не проходит оплата

### ISSUE THREAD

**Issue by Merkost** [Tinkoff/AcquiringSdkAndroid#194]
Здравствуйте!

Не проходит оплата. 

После ввода карты и нажатия кнопки оплатить получаю следующую ошибку: `Tinkoff Acquiring SDK: === Got server response: {"Success":false,"ErrorCode":"309","Message":"Неверные параметры.","Details":"{request.validate.expected.receipt}"}`.

`Parameters: {"Language":"EN","DATA":{"chargeFlag":"false","connection_type":"mobile_sdk","device_model":"Pixel 7 Pro","sdk_version":"2.12.0","software_version":"33"},"Amount":"10000","CustomerKey":"+71234567890","TerminalKey":"**********","Token":"**********","OrderId":"********"}`

Документ с кодами ошибок и их подробным описанием удален из репозитория, поэтому что за неверные параметры мне неизвестно.

**Comment by jQwout** [comment]
Здравствуйте!

Ошибки можно посмотреть в этой документации.
https://tinkoff.github.io/api_asdk/#section/Kody-oshibok

В вашем случае  данная ошибка может означать. - Поле Receipt не должно быть пустым.

**Comment by Merkost** [comment]
Спасибо!
