### ISSUE TITLE
Google Pay не хочет платить.

### ISSUE THREAD

**Issue by lifeyonet** [Tinkoff/AcquiringSdkAndroid#38]
Доброе время суток.
Есть приложение через которое успешно платят, постоянно, каждый день.
Пытаюсь собрать новую версию, попытка выполнить google pay и падает прямо на моменте открытия 1-го "окна" с сообщением  "Не удалось выполнить запрос  Этот продавец не зарегистрирован в сервисе google pay".
Если в тот же самый код проставляю данные как из тестового приложения TestSDK и пр. все открывается.
В логе нет ничего, он даже не зовется ни разу. И запросы никуда никакие не идут.
Пробовал как в документации и уже  иными способами вроде:
PendingIntent pi = tk.createGooglePayPendingIntentForResult(me, params, pay,8442);
try {
                pi.send();
}
Поведение одинаково. Оплата не google pay при этом открывается без проблем для этого терминала/пароля.
Подставляю данные свои в тестовое приложение - ошибка и отсутствие логов одинаково. 
Есть только одно подозрение в продуктиве возможно приложение с API ниже 2.*  не могу проверить, исходники старые вне доступа в ближайшее время.
Что делать?

**Comment by MaryAPc** [comment]
Здравствуйте! Скорее всего вам нужно заново пройти регистрацию в Google Pay с новой версией вашего приложения https://services.google.com/fb/forms/googlepayAPIenable/

**Comment by jQwout** [comment]
Здравствуйте!

Поддержки работы Google Pay в ASDK больше не будет.

С Уважением
Команда ASDK
