### ISSUE TITLE
Google pay невозможно выполнить платеж, платеж не усрешный

### ISSUE THREAD

**Issue by MarkD1916** [Tinkoff/AcquiringSdkAndroid#48]
Добрый день! Сейчас стараюсь настроить работу google pay, пытаюсь сделать тестовый платеж и получаю следующую ошибку. Платеж через банковскую карту на тот же терминал проходит без проблем

![изображение](https://user-images.githubusercontent.com/64790102/115416316-57b34c00-a200-11eb-85c3-af206f084a90.png)

В чем может быть причина ошибки? Заранее благодарю за ответ

**Comment by MarkD1916** [comment]
![Снимок экрана 2021-04-20 в 17 50 22](https://user-images.githubusercontent.com/64790102/115416953-e32cdd00-a200-11eb-876b-60b7ce5515a0.png)
Указал тестовую среду

**Comment by MaryAPc** [comment]
Здравствуйте! Если вы хотите провести тестовый платеж через Google Pay без списания средств, то вам нужно использовать еще и тестовое окружение SDK, установив isDeveloperMode = true. Сейчас по вашим логам вижу, что используется прод окружение.

В целом, для проведения тестового платежа, вам нужно указать:
Sdk AcquiringSdk.isDeveloperMode = true
тестовое окружение GP WalletConstants.ENVIRONMENT_TEST
и использовать DEMO терминал (но может сработать и прод терминал, нужно проверить)

У гугла довольно много нюансов к проведению тестовых и реальных платежей, если еще будут проблемы - пишите)

**Comment by MarkD1916** [comment]
Спасибо)
Оплату провожу с реальной дебетовой карты 
![изображение](https://user-images.githubusercontent.com/64790102/115527915-3010c200-a29a-11eb-9386-9a7695236927.png)

![Снимок экрана 2021-04-21 в 12 07 59](https://user-images.githubusercontent.com/64790102/115527938-399a2a00-a29a-11eb-886b-9a96a03e3078.png)

![Снимок экрана 2021-04-21 в 12 08 17](https://user-images.githubusercontent.com/64790102/115527970-43239200-a29a-11eb-9f9d-1d7fb56e029d.png)

Вот такая ошибка. Владелец бизнеса зарегистрировался в google business console, так же отправлял письмо в Тинькофф, но для того, чтобы закончить процесс интеграции google api нужны скрины удачного платежа - иначе ошибка "Продавец не зарегистрирован в google pay", в WalletConstants.ENVIRONMENT_TEST по идее не требуется регистрация и интеграция гугл апи

**Comment by MaryAPc** [comment]
Можете тогда прислать paymentId такой неуспешной операции? я перешлю коллегам, посмотрят в чем может быть причина

**Comment by MarkD1916** [comment]
Да конечно, вот
"PaymentId":"700000106841"

**Comment by MaryAPc** [comment]
Попробуйте использовать прод терминал (без DEMO)
Остальные настройки оставить

**Comment by MarkD1916** [comment]
Сделал - теперь в логах ошибка "Не получилось пополнить карту. Свяжитесь с поддержкой"
"PaymentId":"700000114705"

![изображение](https://user-images.githubusercontent.com/64790102/115856642-69ca0000-a435-11eb-89b6-f44724e40daa.png)

**Comment by MaryAPc** [comment]
Добрый день! Попробуйте повторть операцию, проблему должны были устранить

**Comment by babazhanov** [comment]
Добрый день!
Настраиваю Google Pay. Не находит терминал, пробовал и тестовый, и рабочий.

`val googleParams = GooglePayParams(
            terminalKey = TERMINAL_ID,
            environment = WalletConstants.ENVIRONMENT_TEST // тестовое окружение
        )`

`AcquiringSdk.isDeveloperMode = true
AcquiringSdk.isDebug = true`

Логи:
`I/System.out: Tinkoff Acquiring SDK: === Sending POST request to https://rest-api-test.tcsbank.ru/v2/Init
I/System.out: Tinkoff Acquiring SDK: === Got server response: {"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Терминал не найден."}
I/System.out: Tinkoff Acquiring SDK: === Request done with fail`

**Comment by jQwout** [comment]
Здравствуйте!

Поддержки работы Google Pay в ASDK больше не будет.

С Уважением
Команда ASDK
