### ISSUE TITLE
Поддержка 12 андроида.

### ISSUE THREAD

**Issue by SamKotlinFisher** [Tinkoff/AcquiringSdkAndroid#65]
При попытке поднять compileSdkVersion и targetSdkVersion до 31, перестают работать быстрые платежи на некоторых устройствах. На экране выбора приложения банка для обработки быстрого платежа получаем ошибку, что таких приложений нет. Если допустим опустить эти два поля до значения 29, то всё начинает работать и приложения банков начинают отображаться для выбора. Версия библиотеки 2.4.1. Устройства Pixel 3 c 12 андроидом и xiaomi Mi 9T pro с 11 андроидом стабильно воспроизводят проблему. На samsung galaxy a11 c 10 андроидом работает всегда, независимо от compileSdkVersion и targetSdkVersion. Поэтому не на всех устройствах удаётся воспроизвести проблему.

**Comment by IlnarH** [comment]
Здравствуйте, сделаем необходимые доработки, думаю, займет около пары недель; пишите если обнаружите еще какие-либо проблемы.

**Comment by IlnarH** [comment]
Версия [2.5.0](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/releases/tag/v2.5.0) с необходимыми доработками в релизе.
