### ISSUE TITLE
Остаётся открытой прозрачная PaymentActivity после закрытия экрана со списком банков СБП

### ISSUE THREAD

**Issue by andreybgm** [Tinkoff/AcquiringSdkAndroid#68]
В версии 2.4.1 sdk появилась возможность проводить оплату по СБП с существующим paymentId.

В нашем проекте оплату вызываем следующим образом:
```
tinkoffAcquiring.payWithSbp(paymentId)
  .subscribe(object : PaymentListener {
      override fun onUiNeeded(state: AsdkState) {
        tinkoffAcquiring.openPaymentScreen(fragment, paymentOptions, requestCode, state)
      }
    }
  )
  .start()
```
 
В результате появляется диалог выбора банка.

Проблема: если закрыть этот диалог, то остаётся открытым прозрачный экран sdk PaymentActivity, и пользователь не может взаимодействовать с нашим приложением, пока не нажмёт back.

Вероятно, в `ui.activities.PaymentActivity` не предусмотрен кейс, когда экран открывается со стейтом `AsdkState.BrowseFpsBankState`:
https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/blob/e94931fc1b1d44c98537d865dc8432a87289867c/ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/PaymentActivity.kt#L102

**Comment by IlnarH** [comment]
Здравствуйте, поправим.

**Comment by IlnarH** [comment]
Версия с доработками [2.5.1](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/releases/tag/v2.5.1) в релизе.

**Comment by andreybgm** [comment]
Спасибо!
