### ISSUE TITLE
Проблемы с определением банков для оплаты через СБП

### ISSUE THREAD

**Issue by andreybgm** [Tinkoff/AcquiringSdkAndroid#69]
В sdk реализован следующий сбособ определения установленных банковских приложений:
https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/blob/e94931fc1b1d44c98537d865dc8432a87289867c/ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/PaymentActivity.kt#L176
```
if (!banks.isNullOrEmpty() && Build.VERSION.SDK_INT < Build.VERSION_CODES.R) {
  packageManager.queryIntentActivities(...)
} else {
  startActivityForResult(...)
}
```

Проблема с `packageManager.queryIntentActivities(...)`. Если для какого-либо банковского приложения в системных настройках опция "Открывать поддерживаемые ссылки" установлена в "Разрешить" вместо "Всегда спрашивать", то в диалоге выбора показывается только это приложение. Если несколько таких приложений, то показываются все приложения с "Разрешить", при этом приложения с "Всегда спрашивать" не показываются. Для пользователя будет совсем неочевидно, почему какие-то банки есть в выборе, а каких-то нет.
 
Проблема с `startActivityForResult(...)`. В этом случае открывается системный диалог выбора приложений. В этом списке есть дефолтный браузер (см. скриншот "системный_диалог_выбора_приложений.png").
Если пользователь выберет "Всегда", то в следующий раз он не сможет выбрать другой банк, предварительно не удалив настройки по умолчанию (см. скриншот "альфа_была_выбрана_всегда.png").
Ещё бОльшая проблема, если выбрать открывать в Chrome "Всегда". У Chrome в системных настройках пункт "Открывать по умолчанию" не показывается. Чтобы его увидеть, нужно сначала отключить приложение.
Типичный пользователь явно не будет разбираться с этими особенностями android.
Проверялось на Android Sdk 30, Acquiring Sdk 2.4.3.

Коллегам из Яндекса для другого проекта разработчиками СБП был предоставлен пример с рекомендуемым способом определения банков (ссылка есть в исходном обращении в теходдержку № 785251). Кратко алгоритм можно сформулировать так:
- Из packageManager.queryIntentActivities(...) получить список приложений. Убрать из результата браузеры.
- Из packageManager.getInstalledApplications(...) получить все приложения на устройстве. Оставить только приложения банков.
- Объединить эти два списка.

Можете ли вы рассмотреть возможность внесения изменений в sdk по этим проблемам?

системный_диалог_выбора_приложений.png:
![системный_диалог_выбора_приложений](https://user-images.githubusercontent.com/11777297/142887409-c0ddb2dd-7068-4053-a68c-0e9cc394cb98.png)

альфа_была_выбрана_всегда.png:
![альфа_была_выбрана_всегда](https://user-images.githubusercontent.com/11777297/142887860-43b56025-73dd-47bc-b43a-5531883e5d27.png)

**Comment by IlnarH** [comment]
Здравствуйте, спасибо за подробное объяснение; в приведенном алгоритме немного смущает второй шаг ("получить все приложения на устройстве. Оставить только приложения банков") - в скинутом примере зашит список банков `predefinedApps` и не очень понятно откуда он берется, не уточняла ли поддержка СБП что-нибудь по этому поводу? Может, он указан где-то в официальной документации?

**Comment by andreybgm** [comment]
> в скинутом примере зашит список банков predefinedApps и не очень понятно откуда он берется

Список загружается из https://qr.nspk.ru/.well-known/assetlinks.json (см. `RemoteRepository.loadAppPackages()`). Не думаю, что есть существенный смысл ещё и отдельно зашивать список банков.
У вас в ASDK тоже есть загрузка этого списка :)

https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/blob/e94931fc1b1d44c98537d865dc8432a87289867c/ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/NspkClient.kt#L35

**Comment by IlnarH** [comment]
Спасибо, тогда для `queryIntentActivities` реализуем алгоритм аналогичный тому что в примере без предзашитого списка, а при запуске `startActivityForResult` вместо оригинального `intent` используем `Intent.createChooser`.

**Comment by andreybgm** [comment]
> при запуске startActivityForResult вместо оригинального intent используем Intent.createChooser

Уточните, пожалуйста. В какой ситуации будет использоваться chooser? Останется условие `Build.VERSION.SDK_INT < Build.VERSION_CODES.R`? Если да, то зачем?

**Comment by IlnarH** [comment]
Chooser будет использоваться если не пройдет условие `Build.VERSION.SDK_INT < Build.VERSION_CODES.R`, т.е. для решения этой проблемы: 
> Если пользователь выберет "Всегда", то в следующий раз он не сможет выбрать другой банк, предварительно не удалив настройки по умолчанию

Условие планируется оставить; оно было добавлено, т.к. начиная c Android 11 (API 30) для получения списка установленных приложений требуется dangerous разрешение `QUERY_ALL_PACKAGES` (https://developer.android.com/training/package-visibility) использование которого приложения должны обосновывать для Google Play; мы посчитали, что добавление этого разрешения в SDK (или заявление, что это разрешение является необходимым для его работоспособности) излишне затруднит интеграцию для потребителей.

**Comment by andreybgm** [comment]
Для sdk 30+ нужно в манифесте задекларировать интент для СБП (https://developer.android.com/training/package-visibility/declaring). Пермишн не понадобится тогда. В примере это есть.

```
<queries>
    <intent>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="https" android:host="qr.nspk.ru"/>
    </intent>
</queries>
```

Можно либо в sdk это добавить, либо отразить в документации, чтобы клиенты с СБП добавили к себе в приложения.

**Comment by IlnarH** [comment]
Спасибо, кажется, пропустили этот момент; тогда проверку на версию уберем и chooser останется только для случая, когда мы не смогли загрузить список пакетов банков приложений.

**Comment by IlnarH** [comment]
Версия с доработками [2.5.1](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/releases/tag/v2.5.1) в релизе.

**Comment by andreybgm** [comment]
Спасибо!
