### ISSUE TITLE
SBP error SDK v2.5.4

### ISSUE THREAD

**Issue by edgartomasov** [Tinkoff/AcquiringSdkAndroid#75]
Добрый день.

Обновили SDK до версии 2.5.4 в андроид проекте.
После обновления метод вызова СБП перестал работать.
`tinkoffAcquiring.payWithSbp(activity, paymentOptions, REQUEST_CODE_TINKOFF_PAYMENT)`

Лог:
`I/System.out: Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/Init
I/System.out: Tinkoff Acquiring SDK: === Got server response: {"Success":true,"ErrorCode":"0","TerminalKey":"161174######DEMO","Status":"NEW","PaymentId":"930560717","OrderId":"109","Amount":619000,"PaymentURL":"https://securepay.tinkoff.ru/new/diybkQhC"}
I/System.out: Tinkoff Acquiring SDK: === Request done with success, sent for processing
I/System.out: Tinkoff Acquiring SDK: === Parameters: {"PaymentId":"930560717","TerminalKey":"161174######DEMO","DataType":"PAYLOAD"}
I/System.out: Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/GetQr
I/System.out: Tinkoff Acquiring SDK: === Got server response: {"Success":false,"ErrorCode":"9999","Message":"Неверные параметры.","Details":"Поле Token не должно быть пустым."}
I/System.out: Tinkoff Acquiring SDK: === Request done with fail`

**Comment by IlnarH** [comment]
Здравствуйте, а с какой версии SDK обновляетесь?

**Comment by edgartomasov** [comment]
2.3.0

**Comment by IlnarH** [comment]
Уточню у коллег, вернусь с ответом.

**Comment by edgartomasov** [comment]
Предполагаю, что дело не в TerminalKey, так как вернув версию 2.3.0, я тоже получаю ошибку, но другую. Раньше все работало.

TerminalKey - 1611742090893DEMO

```
val tinkoffAcquiring =
            TinkoffAcquiring(payment.terminal_key!!, payment.terminal_pass!!, DEFAULT_PUBLIC_KEY)

tinkoffAcquiring.payWithSbp(activity, paymentOptions, REQUEST_CODE_TINKOFF_PAYMENT)
```

`I/System.out: Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/Init
I/System.out: Tinkoff Acquiring SDK: === Got server response: {"Success":true,"ErrorCode":"0","TerminalKey":"1611742090893DEMO","Status":"NEW","PaymentId":"949434214","OrderId":"112","Amount":619000,"PaymentURL":"https://securepay.tinkoff.ru/new/MlaHkQ59"}
I/System.out: Tinkoff Acquiring SDK: === Request done with success, sent for processing
I/System.out: Tinkoff Acquiring SDK: === Parameters: {"PaymentId":"949434214","TerminalKey":"1611742090893DEMO","DataType":"PAYLOAD","Token":"d444bc115b863a5313ea8856f6884607a351e9205082228d90a374446a811126"}
I/System.out: Tinkoff Acquiring SDK: === Sending POST request to https://securepay.tinkoff.ru/v2/GetQr
I/System.out: Tinkoff Acquiring SDK: === Got server response: {"Success":false,"ErrorCode":"3001","Message":"Оплата через QrPay недоступна"}
I/System.out: Tinkoff Acquiring SDK: === Request done with fail`
