### ISSUE TITLE
Тестовые сервера не работают

### ISSUE THREAD

**Issue by ElfenLiedGH** [Tinkoff/AcquiringSdkAndroid#87]
В демо приложении при попытке оплаты после ввод карты ошибка

Скрин с устройства
![image](https://user-images.githubusercontent.com/9973357/159432955-58a0fb66-808d-4084-8eee-7f833340c2f8.png)
Скрин с консоли
![image](https://user-images.githubusercontent.com/9973357/159433087-72348759-1b0d-43e1-b632-f62dfe7729b3.png)

**Comment by nqkwey** [comment]
Есть какая-нибудь новая информация по этому багу? Проблема все еще актуальна

**Comment by ElfenLiedGH** [comment]
@nqkwey если есть договор, то в лк можно создать терминал с демо доступом и можно будет тестить на боевых серверах
