### ISSUE TITLE
onActivityResult is deprecated

### ISSUE THREAD

**Issue by DmitriyAnt** [Tinkoff/AcquiringSdkAndroid#89]
Планируете ли Вы обновить API?

**Comment by fonrit** [comment]
+1.
Возникает проблема с обработкой результата в compose проекте.
Можете дать ответ

**Comment by IlnarH** [comment]
В течение ближайшего квартала планируется редизайн ASDK с переписыванием значительной части кода, при его разработке будет использоваться Activity Result API.
