### ISSUE TITLE
Возможно ли добавить гибкости с емейлом в чеках

### ISSUE THREAD

**Issue by Eddie980** [Tinkoff/AcquiringSdkAndroid#91]
Если есть чек, но в нём нет телефона или емейла. То при установке флага обязательный емейл, при его вводе на экране реквизитов карты, толку будет ноль. Оплата не пройдёт так как при передаче чека там обязательно нужен емейл! Нельзя ли сделать так что если в чеке нет емейла, то подставлять его с этого экрана где пользователь обязан будет его ввести?

**Comment by IlnarH** [comment]
В версии `2.9.0` добавлен параметр [FeaturesOptions.duplicateEmailToReceipt](https://github.com/Tinkoff/AcquiringSdkAndroid/blob/master/ui/src/main/java/ru/tinkoff/acquiring/sdk/models/options/FeaturesOptions.kt#L115-L121).
